macro(PrepareTests)
	if(WIN32)
		set(LOCAL_PATH "PATH=$ENV{PATH}")
		if(POLYSOLVER_USE_AMGX)
			set(LOCAL_PATH "${LOCAL_PATH};${AMGX_DIR}/lib")
		endif(POLYSOLVER_USE_AMGX)
		set(WORKDIR "${CMAKE_SOURCE_DIR}/Testing/Cases")
		set(CMD_LINE "-l all")
		message("${LOCAL_PATH}")
	endif(WIN32)
endmacro(PrepareTests)